### ISSUE TITLE
A wrong okay sign for the passphrase confirm

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-web-wallet#33]
![image](https://user-images.githubusercontent.com/9711879/55524462-718c9f80-56c8-11e9-9768-1f37596ef554.png)

How to reproduce
1. Put the same passphrase in the passphrase box and the passphrase confirm box,
2. And change the content of the passphrase box.
3. There's still an okay sign on the passphrase confirm box.

**Comment by xpdlf1004** [comment]
Merged 0e288fb73e86e3fd7e16255c26c383a582986839
