### ISSUE TITLE
Change Receiever -> Recipient when send

### ISSUE THREAD

**Issue by YunseonJang** [CodeChain-io/codechain-web-wallet#42]
<img width="375" alt="Screen Shot 2019-04-11 at 11 55 43 PM" src="https://user-images.githubusercontent.com/47103786/56010211-b8f4da80-5d1d-11e9-8fe4-571c9ec8d87e.png">
<img width="375" alt="Screen Shot 2019-04-11 at 11 55 43 PM" src="https://user-images.githubusercontent.com/47103786/56010235-c7db8d00-5d1d-11e9-94a4-991941960980.png">

For consistency, change RECIEVER ADDRESS into RECIPIENT ADDRESS.

**Comment by xpdlf1004** [comment]
Merged 0db7338e0903b24b1b0604080a3dadf6975b026f
