### ISSUE TITLE
Change address name at mint/charge page

### ISSUE THREAD

**Issue by YunseonJang** [CodeChain-io/codechain-web-wallet#45]
Change the name at mint/charge
before: Address 1 (주소 1) / Address 1 (주소 1)
after: Asset Address 1 (자산 주소 1) / CCC Address 1 (CCC 주소 1)
![Screen Shot 2019-04-12 at 3 46 15 PM](https://user-images.githubusercontent.com/47103786/56017404-2151b500-5d3a-11e9-8a44-efece1d76255.png)

**Comment by xpdlf1004** [comment]
Merged dfcacfe056172014bd1187e1b55f5efff87a91d0
