### ISSUE TITLE
Cannot issue asset in Corgi Web Wallet

### ISSUE THREAD

**Issue by YunseonJang** [CodeChain-io/codechain-web-wallet#48]
I keep failing to issue new asset in Corgi. All input fields are fine but it keeps pending forever. Cannot even find in corgi completed/pending txs.

**Comment by joojis** [comment]
The cause of the problem was the RPC server(https://corgi-rpc.codechain.io). Now it's fixed.
Related issue: https://github.com/CodeChain-io/jsonrpc-filter/issues/3
